

# register route 
POST https://ineassignment-1.onrender.com/auth/register 
Content-Type: application/json

{
    "username":"kioken", 
    "password":"kioken"
}

### register route 
POST http://localhost:3000/auth/register 
Content-Type: application/json

{
    "username":"testing2", 
    "password":"hello to all "
}

### get all the users 
GET http://localhost:3000/users/getAllUsers


### login route

POST http://localhost:3000/auth/login
Content-Type: application/json

{    "username":"staffbot", 
    "password":"staffbot"}

### get all the users 
GET http://localhost:3000/users/getUser_information
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvdDMiLCJwYXNzd29yZCI6IiQyYiQxMCRCS2tKa2ZsYUFYYTBTV3RrNi43cXNPTno0QWdMcjk4YTNySjhsamlWa1B6WXpjMXg1TDguZSIsImlhdCI6MTcxOTY5OTMwMSwiZXhwIjoxNzE5Nzg1NzAxfQ.AfiNw94uqI576dW39YsLQyPdDYN6CDIrxMpXQC2wn-w


###u

# GET http://localhost:3000/users/getUser_information 
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvdCIsInBhc3N3b3JkIjoiJDJiJDEwJFZpSXdvTmtPemd3R0lieDg1cDBCS3VtSjl0NFg2bXgzY29RSDJBWTVCdHExSUFUVmtQSEVhIiwiaWF0IjoxNzE5NjkyMzkzLCJleHAiOjE3MTk3Nzg3OTN9.vQXVJmeCxuehYTApQRO1WF0JBQVvNhh9bqkJBTF2-Mo
# ### add menu items 

POST http://localhost:3000/menu/addMenuItem
Content-Type: application/json

{
    "name":"Test Item4",
    "description":"This is a test item",
    "price": 10.99,
    "image": "https://www.google.com",
    "category" :"main courses"
}

###
# 
GET http://localhost:3000/menu/filterMenuItem?category=main courses


###
# 
GET http://localhost:3000/menu/getMenuFromID?menu_id=1

###

GET http://localhost:3000/menu/menuItems

###
GET http://localhost:3000/order/getAllOrders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvdDMiLCJwYXNzd29yZCI6IiQyYiQxMCRCS2tKa2ZsYUFYYTBTV3RrNi43cXNPTno0QWdMcjk4YTNySjhsamlWa1B6WXpjMXg1TDguZSIsImlhdCI6MTcxOTY5OTMwMSwiZXhwIjoxNzE5Nzg1NzAxfQ.AfiNw94uqI576dW39YsLQyPdDYN6CDIrxMpXQC2wn-w

###

GET http://localhost:3000/order/getActiveOrder
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0YWZmYm90IiwicGFzc3dvcmQiOiIkMmIkMTAkZ1E5TmZNanRtVmxhQ1gxY204cDdZZURwbllZdlJNQUVGbWNFa05LakVLL2ZKUS5sRHBPQkMiLCJpYXQiOjE3MTk3NDY1NTksImV4cCI6MTcxOTgzMjk1OX0.T4AMSy1tH-2Q0H92wK9IskTm8giOA4dKEh868BB-THQ


###

POST http://localhost:3000/order/placeOrder
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvdDMiLCJwYXNzd29yZCI6IiQyYiQxMCRCS2tKa2ZsYUFYYTBTV3RrNi43cXNPTno0QWdMcjk4YTNySjhsamlWa1B6WXpjMXg1TDguZSIsImlhdCI6MTcxOTY5OTMwMSwiZXhwIjoxNzE5Nzg1NzAxfQ.AfiNw94uqI576dW39YsLQyPdDYN6CDIrxMpXQC2wn-w

{
    "tableNumber" :7,
    "items":[{
        "menuItem":3,
        "quantity":2
    }]
}



### to delete the order 
DELETE http://localhost:3000/order/removeOrder
Content-Type: application/application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmcxIiwicGFzc3dvcmQiOiIkMmIkMTAkaHg4czJ5RDByWkpvY3ovV1FieExQZTBJM3BUQldrM3AwaGUyYVVqVGptS0ZQT1NqNUxES3UiLCJpYXQiOjE3MTk2NzM0ODksImV4cCI6MTcxOTc1OTg4OX0.CxxT2QBr6I8JDIkAeDTnkcjEHtM_PvFFCLfv8xlXHnQ

{
    "order_id": 1
}
### to update orderInformation
PUT http://localhost:3000/order/updateOrder
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmcxIiwicGFzc3dvcmQiOiIkMmIkMTAkaHg4czJ5RDByWkpvY3ovV1FieExQZTBJM3BUQldrM3AwaGUyYVVqVGptS0ZQT1NqNUxES3UiLCJpYXQiOjE3MTk2NzM0ODksImV4cCI6MTcxOTc1OTg4OX0.CxxT2QBr6I8JDIkAeDTnkcjEHtM_PvFFCLfv8xlXHnQ
{
    "order_Id": 1,
    "updates":{
        "tableNumber": 10
    }
}

### to update orderInformation
POST http://localhost:3000/order/markCompleted
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0YWZmYm90IiwicGFzc3dvcmQiOiIkMmIkMTAkZ1E5TmZNanRtVmxhQ1gxY204cDdZZURwbllZdlJNQUVGbWNFa05LakVLL2ZKUS5sRHBPQkMiLCJpYXQiOjE3MTk3NDY1NTksImV4cCI6MTcxOTgzMjk1OX0.T4AMSy1tH-2Q0H92wK9IskTm8giOA4dKEh868BB-THQ

{
    "order_Id":24
}


### to update orderInformation
POST http://localhost:3000/addStaff
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmcxIiwicGFzc3dvcmQiOiIkMmIkMTAkaHg4czJ5RDByWkpvY3ovV1FieExQZTBJM3BUQldrM3AwaGUyYVVqVGptS0ZQT1NqNUxES3UiLCJpYXQiOjE3MTk2NzM0ODksImV4cCI6MTcxOTc1OTg4OX0.CxxT2QBr6I8JDIkAeDTnkcjEHtM_PvFFCLfv8xlXHnQ

{
    "username":"staffbot", 
    "password":"staffbot"
}


### add to cart 

POST http://localhost:3000/order/addToCart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvdDMiLCJwYXNzd29yZCI6IiQyYiQxMCRCS2tKa2ZsYUFYYTBTV3RrNi43cXNPTno0QWdMcjk4YTNySjhsamlWa1B6WXpjMXg1TDguZSIsImlhdCI6MTcxOTY5OTMwMSwiZXhwIjoxNzE5Nzg1NzAxfQ.AfiNw94uqI576dW39YsLQyPdDYN6CDIrxMpXQC2wn-w

{
    "item_Id":3,
    "quantity":4
}



###

POST http://localhost:3000/order/updateCartQuantity
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvdDMiLCJwYXNzd29yZCI6IiQyYiQxMCRCS2tKa2ZsYUFYYTBTV3RrNi43cXNPTno0QWdMcjk4YTNySjhsamlWa1B6WXpjMXg1TDguZSIsImlhdCI6MTcxOTY5OTMwMSwiZXhwIjoxNzE5Nzg1NzAxfQ.AfiNw94uqI576dW39YsLQyPdDYN6CDIrxMpXQC2wn-w

{
    "menuItem":100,
    "newQuantity":5
}


###

POST http://localhost:3000/order/removeFromCart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvdDMiLCJwYXNzd29yZCI6IiQyYiQxMCRCS2tKa2ZsYUFYYTBTV3RrNi43cXNPTno0QWdMcjk4YTNySjhsamlWa1B6WXpjMXg1TDguZSIsImlhdCI6MTcxOTY5OTMwMSwiZXhwIjoxNzE5Nzg1NzAxfQ.AfiNw94uqI576dW39YsLQyPdDYN6CDIrxMpXQC2wn-w

{
    "menuItem":100,
}


### 
GET http://localhost:3000/order/GetOrder?order_Id=4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvdDMiLCJwYXNzd29yZCI6IiQyYiQxMCRCS2tKa2ZsYUFYYTBTV3RrNi43cXNPTno0QWdMcjk4YTNySjhsamlWa1B6WXpjMXg1TDguZSIsImlhdCI6MTcxOTY5OTMwMSwiZXhwIjoxNzE5Nzg1NzAxfQ.AfiNw94uqI576dW39YsLQyPdDYN6CDIrxMpXQC2wn-w

